YodleePOCApp/YodleePOCApp/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using YodleeDomain.Services.Interfaces;

namespace YodleePOCApp.Controllers
{
    public class AccountController : Controller
    {
        private readonly IAccountsService _accountService;

        public AccountController(IAccountsService accountService)
        {
            _accountService = accountService;
        }

        public async Task<IActionResult> DeleteAsync(int accountId, int connectionId)
        {
            bool result = Request.Headers.TryGetValue("loginName", out StringValues loginName);

            if (!result)
            {
                return BadRequest("Invalid login name.");
            }

            var requestResult = await _accountService.DeleteAccountAsync(accountId, loginName.ToString(), connectionId);

            return requestResult.IsSuccess ? Ok(requestResult) : BadRequest(requestResult);
        }
    }
}

YodleePOCApp/YodleePOCApp/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using YodleeDomain.Models.RequestModels;
using YodleeDomain.Models.ResponseModels;
using YodleeDomain.Services.Interfaces;

namespace YodleePOCApp.Controllers
{
    public class AdminController : Controller
    {
        private readonly IRequestSenderService _requestService;

        public AdminController(IRequestSenderService requestService)
        {
            _requestService = requestService;
        }
        
        public async Task<IActionResult> GetTokenAsync(string loginName)
        {
            // todo: before getting the access token we should register user and subscribe to events
            var authRequest = new AuthRequest(loginName);
            var result = await _requestService.SendRequestAsync<AuthResponse>(authRequest, true);

            return result.IsSuccess ? Ok(result) : BadRequest(result);
        }
    }
}

YodleePOCApp/YodleePOCApp/Controllers/HoldingController.cs
using Microsoft.AspNetCore.Mvc;
using YodleeDomain.Services.Interfaces;
using YodleePOCApp.Responses;

namespace YodleePOCApp.Controllers
{
    public class HoldingController : Controller
    {
        private readonly IHoldingsService _holdingsService;

        public HoldingController(IHoldingsService holdingsService)
        {
            _holdingsService = holdingsService;
        }

        [HttpGet]
        public async Task<IActionResult> HoldingDetailsAsync(int accountId, string accountName)
        {
            var result = new GetHoldingsInfoResult();
            result.Holdings = await _holdingsService.GetHoldingsAsync(accountId);
            result.AccountName = accountName;

            return View(result);
        }
    }
}

YodleePOCApp/YodleePOCApp/Controllers/InstitutionController.cs
using Microsoft.AspNetCore.Mvc;
using YodleeDomain.Models;
using YodleeDomain.Services.Interfaces;
using YodleePOCApp.Responses;

namespace YodleePOCApp.Controllers
{
    public class InstitutionController : Controller
    {
        private readonly IOutsideAssetConnectionService _connectionService;
        private readonly IAccountsService _accountsService;

        public InstitutionController(IOutsideAssetConnectionService connectionService, IAccountsService accountsService)
        {
            _connectionService = connectionService;
            _accountsService = accountsService;
        }

        [HttpGet]
        public async Task<IActionResult> UserInstitutionsAsync(string loginName, int userId)
        {
            var connections = await _connectionService.GetConnectionsAsync(userId);
            var result = new GetInstitutionResult
            {
                Institutions = connections,
                UserNickName = loginName,
                UserId = userId
            };

            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> InstitutionDetailsAsync(int connectionId)
        {
            var result = new GetInstitutionInfoResult();

            var accounts = await _accountsService.GetAccountsAsync(connectionId);

            if (accounts.Any())
            {
                result.Accounts = accounts;
                result.Connection = accounts[0].OutsideAssetConnection;
            }

            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> AddAsync([FromBody]EventCallback eventCallback)
        {
            var result = await _connectionService.SaveConnectionsAsync(eventCallback);
            return result.IsSuccess ? Ok(result) : BadRequest(result);
        }
    }
}

YodleePOCApp/YodleePOCApp/Controllers/UserController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using YodleeDomain.Entities;
using YodleeDomain.Models;
using YodleeDomain.Services.Interfaces;

namespace YodleePOCApp.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IMapper _mapper;

        public UserController(IUserService userService, IMapper mapper)
        {
            _userService = userService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _userService.GetAllAsync();

            return PartialView("_Users", model);
        }

        public async Task<IActionResult> SaveUserAsync([FromBody]User userModel)
        {
            RequestResult<object> result;
            try
            {
                result = await _userService.SaveUserAsync(userModel);
            }
            catch (Exception ex)
            {
                result = new RequestResult<object>
                {
                    Error = _mapper.Map<RequestError>(ex)
                };
            }

            return result.IsSuccess ? Ok(result) : BadRequest(result);
        }
    }
}

YodleePOCApp/YodleePOCApp/Controllers/WebhookController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace YodleePOCApp.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class WebhookController : ControllerBase
    {
        [HttpGet("ping")]
        public IActionResult Ping()
        {
            return Ok("pong");
        }
    }
}

YodleePOCApp/YodleePOCApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace YodleePOCApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

YodleePOCApp/YodleePOCApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace YodleePOCApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

YodleePOCApp/YodleePOCApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace YodleePOCApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

YodleePOCApp/YodleePOCApp/Pages/Index.cshtml
@*@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
    Layout = "_Layout";
}

<div id="container-fastlink">
    <div style="text-align: center;">
        <input type="submit" id="btn-fastlink" value="Link an Account">
    </div>
    <!-- Trigger the modal with a button -->
    <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button>
</div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modal Header</h4>
            </div>
            <div class="modal-body">
                <p>Some text in the modal.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

@section scripts {
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src='https://cdn.yodlee.com/fastlink/v4/initialize.js'></script>
    <script>
        (function (window) {
            console.log($('#myModal'));
            $('#myModal').modal();
            //Open FastLink
            var fastlinkBtn = document.getElementById('btn-fastlink');
            fastlinkBtn.addEventListener(
                'click', 
                function() {
                    window.fastlink.open({
                            fastLinkURL: 'https://fl4.sandbox.yodlee.com/authenticate/restserver/fastlink',
                            accessToken: 'Bearer QjMlz3XmdPRiHkGJ5AKaZ0Zlo8AD',
                            params: {
                                configName : 'LaunchTestConfig'
                            },
                            onSuccess: function (data) {
                                // will be called on success. For list of possible message, refer to onSuccess(data) Method.
                                console.log(data);
                            },
                            onError: function (data) {
                                // will be called on error. For list of possible message, refer to onError(data) Method.
                                console.log(data);
                            },
                            onClose: function (data) {
                                // will be called called to close FastLink. For list of possible message, refer to onClose(data) Method.
                                console.log(data);
                            },
                            onEvent: function (data) {
                                // will be called on intermittent status update.
                                console.log(data);
                            }
                        },
                        'container-fastlink');
                },
                false);
        }(window));
    </script>

}*@

YodleePOCApp/YodleePOCApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - YodleePOCApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/YodleePOCApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="/">YodleePOCApp</a>
            </div>
        </nav>
    </header>
    <div style="padding: 0 100px;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - YodleePOCApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>

YodleePOCApp/YodleePOCApp/Views/Holding/HoldingDetails.cshtml
@{
    ViewData["Title"] = "HoldingDetails";
    Layout = "_Layout";
}

@model YodleePOCApp.Responses.GetHoldingsInfoResult

<h1>Holding Details for account @Model.AccountName</h1>

<div overflow-x: auto;">
    <table id="accountTable" class="table">
        <thead>
            <tr>
                <th>HoldingType</th>
                <th>CreatedDate</th>
                <th>LastUpdated</th>
                <th>CostBasisAmount</th>
                <th>CostBasisCurrency</th>
                <th>Description</th>
                <th>OptionType</th>
                <th>PriceAmount</th>
                <th>PriceCurrency</th>
                <th>Quantity</th>
                <th>Symbol</th>
                <th>ValueAmount</th>
                <th>ValueCurrency</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var holding in Model.Holdings)
            {
                <tr id="@holding.Id">
                    <td class="owerflow-item">
                        @holding.HoldingType
                    </td>
                    <td>@holding.CreatedDate</td>
                    <td>@holding.LastUpdated</td>
                    <td>@($"{holding.CostBasisAmount:C}")</td>
                    <td>@holding.CostBasisCurrency</td>
                    <td>@holding.Description</td>
                    <td>@holding.OptionType</td>
                    <td>@($"{holding.PriceAmount:C}")</td>
                    <td>@holding.PriceCurrency</td>
                    <td>@holding.Quantity</td>
                    <td>@holding.Symbol</td>
                    <td>@($"{holding.ValueAmount:C}")</td>
                    <td>@holding.ValueCurrency</td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="modal fade bd-example-modal-sm" id="editNickNameModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Update account info</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Nickname: </label>&nbsp;<label id="label_nickname"></label>
                        <input id="input_nickname" value="" custom-data="" type="text" class="form-control" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-secondary btn-sm" data-dismiss="modal">Close</button>
                <button type="button" id="saveModal" class="btn btn-outline-success btn-sm">Save</button>
            </div>
        </div>
    </div>
</div>

YodleePOCApp/YodleePOCApp/Views/Institution/InstitutionDetails.cshtml
@{
    ViewData["Title"] = "Auth";
    Layout = "_Layout";
}

@model YodleePOCApp.Responses.GetInstitutionInfoResult

<h3>Accounts</h3>
<div overflow-x: auto;">
    <table id="accountTable" class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Display Name</th>
                <th>Type</th>
                <th>Status</th>
                <th>Balance</th>
                <th>Currency</th>
                <th>Number</th>
                <th>Last Updated</th>
                <th>Last Update Attempt</th>
                <th>Next Update Scheduled</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var account in Model.Accounts)
            {
                <tr id="@account.Id">
                    <td class="owerflow-item">
                        @account.AccountName
                        <i class="fa fa-edit" value='{"id":"@account.Id","name":"@account.AccountName","originName":"@account.DisplayedName"}'></i>
                    </td>
                    <td>@account.DisplayedName</td>
                    <td>@account.AccountType</td>
                    <td>@account.AccountStatus</td>
                    <td>@($"{account.Amount:C}")</td>
                    <td>@account.Currency</td>
                    <td>@account.AccountNumber</td>
                    <td>@($"{account.LastUpdated:MM/dd/yyyy}")</td>
                    <td>@(account.LastUpdateAttempt.HasValue ? $"{account.LastUpdateAttempt.Value:MM/dd/yyyy}" : null)</td>
                    <td>@(account.NextUpdateScheduled.HasValue ? ($"{account.NextUpdateScheduled.Value:MM/dd/yyyy}") : null)</td>
                    @if (account.AccountType == "OTHER")
                    {
                        <td>@Html.ActionLink("View Holdings", "HoldingDetails", "Holding", new { accountId = account.Id, accountName = account.DisplayedName })</td>
                    }
                    else
                    {
                        <td></td>
                    }
                    <td id="exclude-account-btn" style="cursor: pointer;color: red;" onclick="excludeAccount(event, @account.Id, @account.OutsideAssetConnectionId)">Delete</td>
                </tr>
            }
        </tbody>
    </table>
</div>

YodleePOCApp/YodleePOCApp/Views/Institution/UserInstitutions.cshtml
@{

    ViewData["Title"] = "Institutions";
    Layout = "_Layout";
}
@model YodleePOCApp.Responses.GetInstitutionResult
<div class="row " style="margin: 15px;">
    <div class="col-md-12">
        <div class="row justify-content-md-center">
            <div class="col-md-12">
                <table id="institutionTable" class="table">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Institution Name</th>
                            <th>Last Updated Date</th>
                            <th>Last Updated Attempt Date</th>
                            <th>Next Update Scheduled Date</th>
                            <th>Count of Accounts</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var inst in Model.Institutions)
                        {
                            <tr>
                                <td class="owerflow-item">@inst.Id</td>
                                <td class="owerflow-item">@inst.ProviderName</td>
                                <td class="owerflow-item">@inst.LastUpdated?.ToShortDateString()</td>
                                <td class="owerflow-item">@inst.LastUpdatedAttempt?.ToShortDateString()</td>
                                <td class="owerflow-item">@inst.NextUpdateScheduled?.ToShortDateString()</td>
                                <td class="owerflow-item">@inst.Accounts.Count</td>
                                <td class="owerflow-item">@inst.Status</td>
                                <th>
                                    @Html.ActionLink("View Accounts", "InstitutionDetails", "Institution", new { connectionId = inst.Id })
                                </th>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="form-group col-4 text-right">
                <button class="btn btn-primary" id="btn-fastlink">Link Account</button>
            </div>
        </div>

        <div class="modal" id="assetsModal" role="dialog" aria-hidden="true" tabindex="-1">
            <div>
                <div id="container-fastlink">
            </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src='https://cdn.yodlee.com/fastlink/v4/initialize.js'></script>
    <script>
        (function(window) {
            //Open FastLink
            selectedLoginName = @Html.Raw(Json.Serialize(@Model.UserNickName));
            selectedUserId = @Html.Raw(Json.Serialize(@Model.UserId));
            
            // save data to lcoalstorage
            localStorage.setItem("selectedLoginName", selectedLoginName);
            localStorage.setItem("selectedUserId", selectedUserId);

            var fastlinkBtn = document.getElementById('btn-fastlink');
            fastlinkBtn.addEventListener(
                'click',
                function() {
                    requestService.post(`/admin/GetToken?loginName=${selectedLoginName}`,
                        null,
                        (response) => {
                            let token = response.result.token.accessToken;
                            $('#assetsModal').modal();
                            window.fastlink.open({
                                    fastLinkURL: 'https://fl4.preprod.yodlee.com/authenticate/USDevexPreProd3-185/fastlink?channelAppName=usdevexpreprod3',
                                    accessToken: `Bearer ${token}`,
                                    params: {
                                        configName: 'LaunchTestConfig'
                                    },
                                    onSuccess: function(data) {
                                        // will be called on success. For list of possible message, refer to onSuccess(data) Method.
                                        console.log(`On Success data:`);
                                        console.log(data);
                                    },
                                    onError: function(data) {

                                        // will be called on error. For list of possible message, refer to onError(data) Method.
                                        console.log(data);
                                    },
                                    onClose: function(data) {
                                        $('#assetsModal').modal('hide');

                                        if (data) {
                                            if (data.action === "exit" && data.fnToCall === "accountStatus" && data.sites.length > 0) {
                                                let eventData = data.sites[0];
                                                eventData.accessToken = token;
                                                eventData.userId = selectedUserId;

                                                requestService.post('add',
                                                    eventData,
                                                    (saveResponse) => {
                                                        if (saveResponse.isSuccess) {
                                                            window.location.href = window.location.origin + "/Institution/InstitutionDetails?connectionId=" + saveResponse.result.id; // navigate to connection details page
                                                        }
                                                    });
                                            }
                                        }
                                        // will be called called to close FastLink. For list of possible message, refer to onClose(data) Method.
                                        console.log(data);
                                    },
                                    onEvent: function(data) {
                                        // will be called on intermittent status update.
                                        console.log("Event received:");
                                        console.log(data);
                                    }
                                },
                                'container-fastlink');
                        },
                        false);
                });
        }(window));
    </script>
}

YodleePOCApp/YodleePOCApp/Views/User/_Users.cshtml
@model List<YodleeDomain.Entities.User>
@{

    Layout = "_Layout";
}
<div class="center-blc">

    <div class="col-md-8 justify-content-center">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        ID
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        Email
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var user in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(x => user.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => user.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => user.Email)
                        </td>

                        <td>
                            @Html.ActionLink("Go", "UserInstitutions", "Institution", new { loginName = user.NickName, userId = user.Id })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <button class="btn btn-info" id="createUserBtn">Create User</button>
    </div>
    <div class="modal" id="createUserModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Add New User</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="newUserForm">
                    <div class="modal-body">
                        <div class="input-item">
                            <label for="userName" class="">User Name</label>
                            <input class="form-control" id="userName" type="text" placeholder="User Name" required>
                        </div>
                        <div class="input-item">
                            <label for="userId" class="">User ID</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">&#64;</span>
                                </div>
                                <input class="form-control" id="userId" type="text" placeholder="User ID" required>
                            </div>
                        </div>
                        <div class="input-item">
                            <label for="email" class="">Email</label>
                            <input class="form-control" id="email" type="email" placeholder="Email" required>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Save</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header">
            <img height="200px" width="200px" src="https://upload.wikimedia.org/wikipedia/commons/f/f9/Phoenicopterus_ruber_in_S%C3%A3o_Paulo_Zoo.jpg" class="rounded mr-2" alt="...">
            <strong class="mr-auto">Bootstrap</strong>
            <small class="text-muted">11 mins ago</small>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="toast-body">
            Hello, world! This is a toast message.
        </div>
    </div>
</div>

@section Scripts {
<script>
    (function(window) {
        var createUserBtn = document.getElementById('createUserBtn');
        var newUserForm = document.getElementById('newUserForm');

        createUserBtn.addEventListener('click', () => {
            $('#createUserModal').modal();
             
        });

        newUserForm.addEventListener('submit', function (event) {
            var nickName = document.getElementById('userId').value;
            var email = document.getElementById('email').value;
            var name = document.getElementById('userName').value;
            var newUser = {
                nickName: nickName,
                email: email,
                name: name,
            };
            requestService.post('/user/SaveUser', newUser, function (response) {

                if (response.isSuccess) {
                    toastr.success('New user has been created!');
                    $('#createUserModal').modal('hide');

                    window.location.reload();
                } else {
                    toastr.error('Failed to save new user into database.');
                }
            });
            event.preventDefault();
            event.stopPropagation();
        });
    }(window));
</script>
}